services:
  plast-mem-db:
    image: paradedb/paradedb:latest
    container_name: plast-mem-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=paradedb # TODO: from env
      - POSTGRES_PASSWORD=0721001f-18f7-452a-9700-6cd4a852633d # TODO: from env
      - POSTGRES_DB=paradedb # TODO: form env
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/
